dist: trusty
sudo: false

branches:
  only:
    - gh-pages

# Install Helm and Kubeval
before_install:
  - wget https://kubernetes-helm.storage.googleapis.com/helm-v2.13.1-linux-amd64.tar.gz
  - tar xzvf helm-v2.13.1-linux-amd64.tar.gz
  - mv linux-amd64/helm helm
  - chmod u+x helm
  - wget https://github.com/garethr/kubeval/releases/download/0.10.0/kubeval-linux-amd64.tar.gz
  - tar xzvf kubeval-linux-amd64.tar.gz
  - chmod u+x kubeval
  - mv helm kubeval /home/travis/bin/
  - helm init -c

env:
  # Which K8s version are we going to validate against
  - KUBERNETES_VERSION="1.10.9"

# Run some tests
script:
  # Lint Todo App chart syntax
  - helm lint charts/todo
  # Validate generated K8s manifests
  - mkdir manifests
  - helm template charts/todo --output-dir manifests
  - find manifests/ -name '*.yaml' | grep -v crd | xargs kubeval -v $KUBERNETES_VERSION

after_success:
  # Build Todo App Chart and update Chart Index
  - helm package charts/todo
  - helm repo index --url https://gravitonian.github.io/helm-charts .
  # Publish new Todo App Chart
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add .
  - git status
  - git commit --message "Travis CI build: $TRAVIS_BUILD_NUMBER"
  - git remote add origin-pages https://${GITHUB_TOKEN}@github.com/gravitonian/helm-charts.git > /dev/null 2>&1
  - git push --quiet --set-upstream origin-pages gh-pages


